### ISSUE TITLE
Some sensors update too frequently

### ISSUE THREAD

**Issue by jagheterfredrik** [jagheterfredrik/wallbox-mqtt-bridge#10]
Charging power and added energy can change every `polling_interval_seconds` and thus send a lot of values to HA. We should rate limit these frequently changing sensors without sacrificing update speed of the less frequently changing ones (e.g. lock status). So keep polling every second but rate limit the main offenders.

**Comment by tronikos** [comment]
Why is this an issue?

I have a Wallbox Pulsar Plus paired with a power meter and I have the internal mosquitto forward everything to my MQTT instance that Home Assistant uses without any issues. I have dozens of sensors that get updated every second. I have a template sensor that computes the charging power from those exported MQTT values so I'm not affected by this but it would be good for users to have access to an accurate almost instant charging power. e.g. if you want to pause charging before unplugging with your current fix you have to wait up to 10 seconds to verify there is indeed no power before unplugging. Maybe a better fix is to do something similar to the delta functionality of esphome, see https://esphome.io/components/sensor/index.html#delta That way pausing or changing the max current will immediately be reflected in the charging power sensor.

**Comment by jagheterfredrik** [comment]
I’ve had issues with sensors reporting every second making history really slow in HA

**Comment by jagheterfredrik** [comment]
For unplugging the car won’t let you disconnect if there’s power anyway. I’d be down for a smarter rate limit
