### ISSUE TITLE
Use faster redis hmget instead of hget

### ISSUE THREAD

**Issue by tronikos** [jagheterfredrik/wallbox-mqtt-bridge#27]
Every second the code issues 6 redis hget calls. 5 of the hget calls are over the m2w while 1 is over the state.

I did a small benchmark using hmget calls and it was 2x faster. See https://www.diffchecker.com/m8M9fDLb/
Note this was over 1000 iterations.

@jagheterfredrik do you think it's worth batching the redis calls similarly to doing a single sql query every second? Or the efficiency gains aren't worth it due to increased code complexity?

**Comment by jagheterfredrik** [comment]
Unless it's abstracted away in a nice way, I think it'd add a lot of complexity, redis is super fast especially on localhost

**Comment by tronikos** [comment]
FYI, my measurements were on localhost. 
I can't think of a nice way abstracting this without adding complexity. At least https://github.com/jagheterfredrik/wallbox-mqtt-bridge/pull/29 should help a bit here. Closing.
