### ISSUE TITLE
Not compatible with the new Pulsar Plus (PM3)

### ISSUE THREAD

**Issue by niouniou49** [jagheterfredrik/wallbox-mqtt-bridge#32]
hello, i installed all your files in /home/root/mqtt-bridge
launch the ./install.sh but got some errors below

Setting up virtual environment
./install.sh: line 24: python3: command not found
Installing Python dependencies
./install.sh: line 27: venv/bin/pip: No such file or directory
Setting up the MQTT bridge systemd service
ln: failed to create symbolic link '/lib/systemd/system/mqtt-bridge.service': File exists

Enable the service to start on boot..
..and launch the service now
Sleeping for 3 seconds before checking the status of the systemd service
● mqtt-bridge.service - MQTT Bridge
     Loaded: loaded (/etc/systemd/system/mqtt-bridge.service; enabled; vendor preset: disabled)
     Active: activating (auto-restart) (Result: exit-code) since Sun 2023-12-17 19:49:40 CET; 925ms ago
    Process: 29554 ExecStart=/home/root/mqtt-bridge/venv/bin/python3 /home/root/mqtt-bridge/bridge.py (code=exited, status=203/EXEC)
   Main PID: 29554 (code=exited, status=203/EXEC)

Dec 17 19:49:40 WB628598 systemd[1]: mqtt-bridge.service: Main process exited, code=exited, status=203/EXEC
Dec 17 19:49:40 WB628598 systemd[1]: mqtt-bridge.service: Failed with result 'exit-code'.
root@WB628598:~/mqtt-bridge#

**Comment by jagheterfredrik** [comment]
Looks like you installed twice 👍 no worries

**Comment by jagheterfredrik** [comment]
I was too quick to close this. Seems Wallbox made a new Wallbox version pre-installed with Yocto 4.0 and without Python.

```
root@WB628598:/usr/bin# cat /etc/apt/sources.list
deb http://pulsar-pm3-repo.wall-box.com/ kirkstone main
```

I'll need to investigate.

**Comment by jagheterfredrik** [comment]
I think Wallbox has made a new version of the Wallbox, they seem to call it pm3. I assume it has a Pi Compute Module 4, as it is arm64, which makes sense with the supply of the older CM3+ probably getting really dry.

It comes with Yocto 4.0 (Kirkstone) but without Python installed.

**Comment by jagheterfredrik** [comment]
During a tired investigation yesterday, we checked for /usr/bin/python3 but never checked for /usr/bin/python. Awaiting testing by @niouniou49

**Comment by niouniou49** [comment]
root@WB628598:/usr/bin# cat /etc/os-release
ID=wb-poky
NAME="Poky-based Wallbox distribution"
VERSION="1.0 (kirkstone)"
VERSION_ID=1.0
PRETTY_NAME="Poky-based Wallbox distribution 1.0 (kirkstone)"
DISTRO_CODENAME="kirkstone"

**Comment by niouniou49** [comment]
no python in usr/bin/

**Comment by jagheterfredrik** [comment]
Could you download this file https://drive.google.com/file/d/1vTCSmfOiUoZ8NvfAQcs1B46QlLHG-733/view, put it on your wallbox and run
```
chmod +x bridge-arm64
./bridge-arm64
```

**Comment by niouniou49** [comment]
root@WB628598:~/mqtt-bridge# ./bridge-arm64
Launching!
{{0} {182 177 1 0} 4}

**Comment by jagheterfredrik** [comment]
Great, now I need to tinker some more.

@tronikos I'm considering porting the app to Go which has great cross-compilation support, doesn't rely on glibc (which is really old on the older Wallbox) if building without cgo and is statically linked by default.

**Comment by tronikos** [comment]
Did you consider using cython? It's harder to get cross-compilation but at least you won't have to port the app to Go.

**Comment by jagheterfredrik** [comment]
No, I really don't want to mess around with linking to the correct glibc 😩

**Comment by jagheterfredrik** [comment]
@niouniou49 I've made a new bridge for you; https://github.com/jagheterfredrik/wallbox-mqtt-bridge-go.
Remove the old bridge and follow the instructions there, you might need to run `systemctl daemon-reload` before the other `systemctl` commands.

**Comment by niouniou49** [comment]
did everything, no error message but i can not see anything in mqtt....
how to check everything works?

**Comment by niouniou49** [comment]
Upload the binary as ~/mqtt-bridge/bridge
Does it mean i need to rename the file [bridge-arm64] to bridge and copy it into the folder home/root/mqtt-bridge  that is on the wallbox?
so all in all i have only 3 files in this folder : bridge , bridge.ini, mqtt-bridge.service

is it correct? that the only files i copied to my wallbox

**Comment by jagheterfredrik** [comment]
That's right: bridge, bridge.ini, mqtt-bridge.service

Look at the logs using `journalctl -fu mqtt-bridge`

**Comment by niouniou49** [comment]
all good now, i can see in mqtt and so my home assistant
only one topic remains : i can not use the 'Wallbox Charging enable' function, it seems not possible to enable/disable the wallbox?
what do u think?

**Comment by jagheterfredrik** [comment]
What does the log say when you try? (journalctl from above)
What state are you in? Car connected? Charging?

**Comment by niouniou49** [comment]
the command journalctl -fu mqtt-bridge just do nothing
<img width="546" alt="Screenshot 2023-12-19 at 17 25 46" src="https://github.com/jagheterfredrik/wallbox-mqtt-bridge/assets/72173152/d81e9cd7-8ebf-4f98-b663-2bedae5e2e48">

**Comment by niouniou49** [comment]
root@WB628598:~/mqtt-bridge# ./bridge bridge.ini
Publishing:  cumulative_added_energy 5.832668e+06
Publishing:  max_charging_current 28
Publishing:  halo_brightness 28
Publishing:  cable_connected 0
Publishing:  charging_power 0
Publishing:  added_range 114
Publishing:  lock 0
Publishing:  charging_enable 0
Publishing:  status Ready
Publishing:  added_energy 13769.5

**Comment by niouniou49** [comment]
when i push the button charging enable then it does 'Setting charging_enable 1'
how to do ''Setting charging_enable 0''? the switch should do 1 when switch on and 0 when switch off, but it does only '1' all the time 
<img width="303" alt="Screenshot 2023-12-19 at 17 31 28" src="https://github.com/jagheterfredrik/wallbox-mqtt-bridge/assets/72173152/e5427978-cd10-403d-8200-01ad38dc51c6">

**Comment by jagheterfredrik** [comment]
Status Ready means you don’t have a car connected. Charge enable only means something when you’re charging. You want lock.

**Comment by jagheterfredrik** [comment]
Any chance you could give me the output of `uname -a`?

**Comment by niouniou49** [comment]
uname -a
root@WB628598:~/mqtt-bridge# uname -a
Linux WB628598 5.4.125 #1 SMP PREEMPT Wed Jun 29 13:43:34 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

root@WB628598:~/mqtt-bridge# uname -m
aarch64

**Comment by niouniou49** [comment]
how to ensure the bridge run all the time?
seems it s not running always
had to do : './bridge bridge.ini' multiple time...

**Comment by jagheterfredrik** [comment]
`systemctl start mqtt-bridge` will run it indefinitely, if you start it manually it will die when you leave ssh

**Comment by niouniou49** [comment]
many thanks for you work, what happen is the wallbox has an electricity shut down and restart after, will mqtt-bridge restart (if i have done once systemctl start mqtt-bridge) ? is there an auto restart ou should it be run manually at each restart?

**Comment by jagheterfredrik** [comment]
If you did `systemctl enable mqtt-bridge` it will auto start

**Comment by niouniou49** [comment]
root@WB628598:~# journalctl -fu mqtt-bridge
Dec 20 11:20:36 WB628598 systemd[1]: mqtt-bridge.service: Failed to get cgroup ID on cgroup /sys/fs/cgroup/unified/system.slice/mqtt-bridge.service, ignoring: Function not implemented

**Comment by jagheterfredrik** [comment]
Never seen before, is it causing issues?

**Comment by niouniou49** [comment]
Don’t think so 😉Sent from my iPhoneOn 20 Dec 2023, at 13:24, Fredrik Gustafsson ***@***.***> wrote:﻿
Never seen before, is it causing issues?
