### ISSUE TITLE
command on osx to scp the files to the wallbox, perhaps it can be updated in the readme

### ISSUE THREAD

**Issue by niouniou49** [jagheterfredrik/wallbox-mqtt-bridge#33]
i had to do the following command to push the files to the wallbox
specially to add -O and -i id_rsa

scp -r -O -i /Users/xxxxxxx/Downloads/wallbox-pwn-main/id_rsa /Users/xxxxxxxxx/Downloads/wallbox-mqtt-bridge-main/mqtt-bridge

**Comment by jagheterfredrik** [comment]
Feel free to open a PR 🙏
