### ISSUE TITLE
Watchdog

### ISSUE THREAD

**Issue by Tony2k** [jagheterfredrik/wallbox-mqtt-bridge#49]
One time a week I have a fault condition so it would be useful to create an automation to restart the Wallbox. Do you think you could add a watchdog or a reboot integration to use with an automation from Homeassistant?

**Comment by jagheterfredrik** [comment]
I don’t think it’s possible to expose a service over MQTT auto discovery. Easiest solution is to make a cron entry on the wallbox executing `systemctl start reboot`. The hard way is publishing a “raw” MQTT message and handle it manually in the bridge.

**Comment by davidKooreman** [comment]
> One time a week I have a fault condition so it would be useful to create an automation to restart the Wallbox. Do you think you could add a watchdog or a reboot integration to use with an automation from Homeassistant?

I have the same problem. After 5 days the data is empty in Home assistant. After rebooting the wallbox its working again

**Comment by jagheterfredrik** [comment]
Are you running the latest version? A memory leak was fixed that could cause instability over time. Upgrade by running the install script again.
