### ISSUE TITLE
Feature Request: WIFI info published to MQTT

### ISSUE THREAD

**Issue by CaptInsano** [jagheterfredrik/wallbox-mqtt-bridge#58]
I was recently debugging a wifi connection issue for my Wallbox Pulsar and it dawned on me that having the WIFI connection info sent to Home Assistant would be really helpful.

I was able to use the iw commands to manually check my info but it would great to be able to monitor it in Home Assistant.

the commands for SSID name and Signal I was using are as follows:

```
root@WBXXXXX:~# iw wlan0 info | grep 'ssid' && iw wlan0 station dump | grep 'signal:'
        ssid MYWIFI
        signal:         -67 [-67] dBm
```

I am not sure if this is the best was of doing it but could something like this be added?

Thanks so much for your work on this.

EDIT: Just thought that maybe adding an IP address sensor might help people also if they wanting to ssh into their wallbox for updates etc?

```
root@WBXXXXXX:~# hostname -i
192.168.X.XXX

```

**Comment by jagheterfredrik** [comment]
This repo is very specific to wallbox and for general monitoring I think it makes more sense to use another solution.

One example is [Telegraf](https://github.com/influxdata/telegraf) which has been [tested before](https://community.home-assistant.io/t/wallbox-pulsar-plus-integration/200339/1148) and sports a [wifi input plugin](https://www.influxdata.com/integration/wireless/) and an [mqtt output plugin](https://www.influxdata.com/integration/mqtt-telegraf-producer/).

**Comment by CaptInsano** [comment]
That is a pity you feel that way about this software. 

I feel that basic WIFI connection info falls into the category of device monitoring very well when wallbox units are known to have WIFI issues (fixed in newer models apparently). 

Similar WIFI information is provided in most Tasmota, WLED, ESPHome devices no matter their specific function

If you ever think about changing this from wont-fix to a possible feature in the future it would be great.

Thanks again for your work on this, is has made my charger a much more reliable unit!

**Comment by jagheterfredrik** [comment]
I agree that it falls into the category of device monitoring, an area where Telegraf shines.

Tasmota, ESPHome and friends are much more generic than this bridge and if the Wallbox was running on an ESP32 this bridge would be a plugin to one of those ecosystems.
