### ISSUE TITLE
Wallbox temperature 

### ISSUE THREAD

**Issue by ffrog8** [jagheterfredrik/wallbox-mqtt-bridge#59]
Any chance of an update that includes temperature? 

I can see some temperature data. I only have a single phase wallbox so can only guess that l2 & l3 would be populated as well?

```
MariaDB [wallbox]> SELECT temp_l1, temp_l2, temp_l3 FROM state_values LIMIT 10;
+---------+---------+---------+
| temp_l1 | temp_l2 | temp_l3 |
+---------+---------+---------+
|      24 |       0 |       0 |
|      24 |       0 |       0 |
|      24 |       0 |       0 |
|      24 |       0 |       0 |
|      24 |       0 |       0 |
|      19 |       0 |       0 |
|      20 |       0 |       0 |
|      22 |       0 |       0 |
|      27 |       0 |       0 |
|      19 |       0 |       0 |
+---------+---------+---------+
10 rows in set (0.00 sec)

MariaDB [wallbox]> SELECT TEMP_PFC, TEMP_PH1, TEMP_PH2 FROM state_values_dc LIMIT 10;
Empty set (0.00 sec)
```

As a side note, I was so happy that I had been ignoring the firmware updates and was still stuck on a pre 6 version. This MQTT bridge for the wallbox is awsome.

**Comment by jagheterfredrik** [comment]
I think that would be doable, could you check if the temperatures are available from redis?

Note that firmware updates don’t break the rooting nor the bridge. Just the ability to root in the first place.

**Comment by ffrog8** [comment]
```
redis-cli -h localhost -p 6379 HMGET m2w "tms.line1.temp_deg.value" "tms.line2.temp_deg.value" "tms.line3.temp_deg.value"
1) "20"
2) "0"
3) "0"
```
Looks like a win. 
Good to know RE firmware.

**Comment by jagheterfredrik** [comment]
Great, do you want to attempt to make a pull request to add the functionality? 🙂

**Comment by ffrog8** [comment]
I had a crack - let me know how it goes.

**Comment by jagheterfredrik** [comment]
Thanks @ffrog8, all merged and released. Run the install script again to update.

**Comment by ffrog8** [comment]
Works like a charm! Excellent.
