### ISSUE TITLE
Doesn't support complicated passwords

### ISSUE THREAD

**Issue by petervk** [jagheterfredrik/wallbox-mqtt-bridge#61]
I had a very complicated password on my mqtt broker because I use a password manager and I couldn't get this to work until I changed the password on my mqtt broker to something simple. I'm guessing some characters weren't being escaped properly?

**Comment by jagheterfredrik** [comment]
It’s read from stdin, removed of newline and spaces and handed over to the ini library. https://github.com/jagheterfredrik/wallbox-mqtt-bridge/blob/ee9112077c70e4e70163e798ba6b5090a971dd74/app/tui.go#L13

It’d be interesting to see what the generated ini contains when it’s not working.

**Comment by petervk** [comment]
I don't want to share my actual password but I can try generating a different random one to see if I can get it to fail. I guess the issue could also be with the MQTT broker somehow not reading the password correctly. I can likely do this later today.

**Comment by jagheterfredrik** [comment]
Feel free to reopen if you ever get around to it.
